spring:
  datasource:
    #url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://localhost:3306/attendance?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: username
    password: password
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 21
      min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false

  mail:
    host: smtp.hostinger.com
    port: 465
    username: your-email
    password: your-email
    protocol: smtp
    properties:
      "mail.smtp.ssl.enable": true
      mail:
        smtp:
          auth: true
server:
   port: 8080 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
      
